name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: svelte

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
        os:
          [
            windows-2019,
            windows-2019,
            windows-2019,
            windows-2019,
            windows-2019,
            windows-2019,
            windows-2019,
            windows-2019,
            windows-2019,
            windows-2019
          ]
    env:
      TURBO_CACHE_KEY: ${{ matrix.os }}-${{ matrix.node-version }}
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm turbo run test
      - name: archive test results
        if: failure()
        shell: bash
        run: find packages -type d -name test-results -not -empty | tar -czf test-results.tar.gz --exclude='*-retry*' --files-from=-
      - name: Upload failed tests screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          retention-days: 3
          name: test-failure-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.node-version }}
          path: test-results.tar.gz
